if getseries2 == 'Light Adolescence':
            woodname21 = LightAdolescence[0]
            woodname22 = LightAdolescence[1]
            woodname23 = LightAdolescence[2]
            woodname24 = LightAdolescence[3]
            woodname25 = LightAdolescence[4]
            woodname26 = LightAdolescence[5]
            woodname27 = LightAdolescence[6]
            woodname28 = LightAdolescence[7]
        elif getseries2 == 'Elder Brilliance':
            woodname21 = ElderBrilliance[0]
            woodname22 = ElderBrilliance[1]
            woodname23 = ElderBrilliance[2]
            woodname24 = ElderBrilliance[3]
            woodname25 = ElderBrilliance[4]
            woodname26 = ElderBrilliance[5]
            woodname27 = ElderBrilliance[6]
            woodname28 = ElderBrilliance[7]
        elif getseries2 == 'Solid Wood':
            woodname21 = SolidWood[0]
            woodname22 = SolidWood[1]
            woodname23 = SolidWood[2]
            woodname24 = SolidWood[3]
            woodname25 = SolidWood[4]
            woodname26 = SolidWood[5]
            woodname27 = SolidWood[6]
            woodname28 = SolidWood[7]
        elif getseries2 == 'Gentlemens Leather':
            woodname21 = GentlemensLeather[0]
            woodname22 = GentlemensLeather[1]
            woodname23 = GentlemensLeather[2]
            woodname24 = GentlemensLeather[3]
            woodname25 = GentlemensLeather[4]
            woodname26 = GentlemensLeather[5]
            woodname27 = GentlemensLeather[6]
            woodname28 = GentlemensLeather[7]
        elif getseries2 == 'Cherry Passion':
            woodname21 = CherryPassion[0]
            woodname22 = CherryPassion[1]
            woodname23 = CherryPassion[2]
            woodname24 = CherryPassion[3]
            woodname25 = CherryPassion[4]
            woodname26 = CherryPassion[5]
            woodname27 = CherryPassion[6]
            woodname28 = CherryPassion[7]
        elif getseries2 == 'Earth Valley':
            woodname21 = EarthValley[0]
            woodname22 = EarthValley[1]
            woodname23 = EarthValley[2]
            woodname24 = EarthValley[3]
            woodname25 = EarthValley[4]
            woodname26 = EarthValley[5]
            woodname27 = EarthValley[6]
            woodname28 = EarthValley[7]
        elif getseries2 == 'Red Inspire':
            woodname21 = RedInspire[0]
            woodname22 = RedInspire[1]
            woodname23 = RedInspire[2]
            woodname24 = RedInspire[3]
            woodname25 = RedInspire[4]
            woodname26 = RedInspire[5]
            woodname27 = RedInspire[6]
            woodname28 = RedInspire[7]
        elif getseries2 == 'Supreme Wood':
            woodname21 = SupremeWood[0]
            woodname22 = SupremeWood[1]
            woodname23 = SupremeWood[2]
            woodname24 = SupremeWood[3]
            woodname25 = SupremeWood[4]
            woodname26 = SupremeWood[5]
            woodname27 = SupremeWood[6]
            woodname28 = SupremeWood[7]
        elif getseries2 == 'Timeless Wisdom':
            woodname21 = TimelessWisdom[0]
            woodname22 = TimelessWisdom[1]
            woodname23 = TimelessWisdom[2]
            woodname24 = TimelessWisdom[3]
            woodname25 = TimelessWisdom[4]
            woodname26 = TimelessWisdom[5]
            woodname27 = TimelessWisdom[6]
            woodname28 = TimelessWisdom[7]
        elif getseries2 == 'Dark Chocolate':
            woodname21 = DarkChocolate[0]
            woodname22 = DarkChocolate[1]
            woodname23 = DarkChocolate[2]
            woodname24 = DarkChocolate[3]
            woodname25 = DarkChocolate[4]
            woodname26 = DarkChocolate[5]
            woodname27 = DarkChocolate[6]
            woodname28 = DarkChocolate[7]